color: true
delay: false
diff: true
exit: true
extension:
  - 'js'

recursive: true
reporter: 'spec'
require: 'mocha-clean'
slow: 75
sort: false
timeout: 2000
ui: 'bdd'
# watch: false
# watch-files:
#   - 'lib/**/*.js'
#   - 'test/**/*.js'
# watch-ignore:
#   - 'lib/vendor'
